<?php

return [
		'user-management' => [		'title' => 'User management',		'fields' => [		],	],
		'permissions' => [		'title' => 'Permissions',		'fields' => [			'title' => 'Title',		],	],
		'roles' => [		'title' => 'Roles',		'fields' => [			'title' => 'Title',			'permission' => 'Permissions',		],	],
		'users' => [		'title' => 'Users',		'fields' => [			'name' => 'Name',			'email' => 'Email',			'password' => 'Password',			'role' => 'Role',			'remember-token' => 'Remember token',			'approved' => 'Approved',			'team' => 'Team',			'account-manager' => 'Account manager',			'agree' => 'Agree',			'banner-color' => 'Banner color',			'address' => 'Address',			'city' => 'City',			'state' => 'State',			'country' => 'Country',			'phone' => 'Phone',			'postcode' => 'Postcode',			'company' => 'Company',			'device' => 'Device',			'locale' => 'Locale',			'login' => 'Login',			'login-date-time' => 'Login date time',			'login-status' => 'Login status',			'logo' => 'Logo',			'mycred-default' => 'Mycred default',			'mycred-default-total' => 'Mycred default total',			'mycred-epp-mycred' => 'Mycred epp mycred',			'owners-email' => 'Owners email',		],	],
		'place' => [		'title' => 'Place',		'fields' => [		],	],
		'state' => [		'title' => 'State',		'fields' => [			'title' => 'Title',			'description' => 'Description',			'latitude' => 'Latitude',			'longitude' => 'longitude',			'featured-image' => 'Featured image',			'country' => 'Country',		],	],
		'country' => [		'title' => 'Country',		'fields' => [			'title' => 'Title',			'description' => 'Description',			'featured-image' => 'Featured image',			'latitude' => 'Latitude',			'longitude' => 'Longitude',			'currency' => 'Currency',			'shortcode' => 'Shortcode',		],	],
		'city' => [		'title' => 'City',		'fields' => [			'title' => 'Title',			'description' => 'Description',			'latitude' => 'Latitude',			'longitude' => 'Longitude',			'featured-image' => 'Featured image',			'state' => 'State',		],	],
		'accommodation' => [		'title' => 'Accommodation',		'fields' => [			'title' => 'Title',			'description' => 'Description',			'contact-no' => 'Contact no',			'accommodation-address' => 'Accommodation address',			'featured-image' => 'Featured image',			'website-address' => 'Website address',			'check-in-time' => 'Check in time',			'check-out-time' => 'Check out time',			'latitude' => 'Latitude',			'longitude' => 'Longitude',			'city' => 'City',		],	],
		'user-actions' => [		'title' => 'User actions',		'created_at' => 'Time',		'fields' => [			'user' => 'User',			'action' => 'Action',			'action-model' => 'Action model',			'action-id' => 'Action id',		],	],
		'teams' => [		'title' => 'Teams',		'fields' => [			'name' => 'Name',		],	],
		'assets-management' => [		'title' => 'Assets management',		'fields' => [		],	],
		'assets-categories' => [		'title' => 'Categories',		'fields' => [		],	],
		'assets-statuses' => [		'title' => 'Statuses',		'fields' => [		],	],
		'assets-locations' => [		'title' => 'Locations',		'fields' => [		],	],
		'assets' => [		'title' => 'Assets',		'fields' => [		],	],
		'assets-history' => [		'title' => 'Assets history',		'created_at' => 'Time',		'fields' => [		],	],
		'basic-crm' => [		'title' => 'Basic CRM',		'fields' => [		],	],
		'crm-statuses' => [		'title' => 'Statuses',		'fields' => [			'title' => 'Title',		],	],
		'crm-customers' => [		'title' => 'Customers',		'fields' => [			'first-name' => 'First name',			'last-name' => 'Last name',			'crm-status' => 'Status',			'email' => 'Email',			'phone' => 'Phone',			'address' => 'Address',			'skype' => 'Skype',			'website' => 'Website',			'description' => 'Description',		],	],
		'crm-notes' => [		'title' => 'Notes',		'fields' => [			'customer' => 'Customer',			'note' => 'Notes',		],	],
		'crm-documents' => [		'title' => 'Documents',		'fields' => [			'customer' => 'Customer',			'name' => 'Title',			'description' => 'Description',			'file' => 'File',		],	],
		'faq-management' => [		'title' => 'FAQ Management',		'fields' => [		],	],
		'faq-categories' => [		'title' => 'Categories',		'fields' => [			'title' => 'Category',		],	],
		'faq-questions' => [		'title' => 'Questions',		'fields' => [			'category' => 'Category',			'question-text' => 'Question',			'answer-text' => 'Answer',		],	],
		'exhibitors' => [		'title' => 'Exhibitors',		'fields' => [			'name' => 'Name',			'description' => 'Description',			'contact' => 'Contact',			'address' => 'Address',			'website' => 'Website',			'category' => 'Category',			'logo' => 'Logo',			'history' => 'History',			'device-id' => 'Device id',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',		],	],
		'field-operator' => [		'title' => 'Field operator',		'fields' => [			'name' => 'Name',			'phone' => 'Phone',			'rating' => 'Rating',			'date-of-birth' => 'Date of birth',			'drivers-license-number' => 'Drivers license number',			'drivers-license-state' => 'Drivers license state',			'drivers-license-expiration-date' => 'Drivers license expiration date',			'relationdeviceid' => 'Relationdeviceid',			'ref-role' => 'Ref role',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',		],	],
		'rooms' => [		'title' => 'Rooms',		'fields' => [			'room-type-and-size' => 'Room type and size',			'bed-size' => 'Bed size',			'featured-image' => 'Featured image',			'max-count' => 'Max count',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',		],	],
		'query' => [		'title' => 'Query',		'fields' => [			'driver-pickup-date-time' => 'Driver pickup date time',			'booking-id' => 'Booking id',			'budget' => 'Budget',			'traveler-name' => 'Traveler name',			'bill-pay' => 'Bill pay',			'no-of-adults' => 'No of adults',			'no-of-children' => 'No of children',			'note' => 'Note',			'status' => 'Status',			'phone' => 'Phone',			'email' => 'Email',			'email-second' => 'Email second',			'traveller-id' => 'Traveller id',			'generated-itinerary' => 'Generated itinerary',			'itinerary-places' => 'Itinerary places',			'agency-id' => 'Agency id',			'agent-id' => 'Agent id',			'meal-day' => 'Meal day',			'meals-supplement' => 'Meals supplement',			'messageidd' => 'Messageidd',			'package-category' => 'Package category',			'pickup-address' => 'Pickup address',			'pickup-location' => 'Pickup location',			'query-feel' => 'Query feel',			'remarks' => 'Remarks',			'score' => 'Score',			'score-new' => 'Score new',			'total-room' => 'Total room',			'total-tour-days' => 'Total tour days',			'tour-cost' => 'Tour cost',			'tour-cost-tax' => 'Tour cost tax',			'tour-id' => 'Tour id',			'tour-name' => 'Tour name',			'tour-location' => 'Tour location',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',		],	],
		'leads' => [		'title' => 'Leads',		'fields' => [			'lead-id' => 'Lead id',			'lead-status' => 'Lead status',			'package-type' => 'Package type',			'date' => 'Date',			'email' => 'Email',			'phone' => 'Phone',			'name' => 'Name',			'adult-guest' => 'Adult guest',			'score' => 'Score',			'kids-guests' => 'Kids guests',			'agent-id' => 'Agent id',			'agency-id' => 'Agency id',			'score-new' => 'Score new',			'lead-feel' => 'Lead feel',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',			'remark' => 'Remark',			'source' => 'Source',			'infant-guest' => 'Infant guest',		],	],
		'field-roals' => [		'title' => 'Field roles',		'fields' => [		],	],
		'driver' => [		'title' => 'Driver',		'fields' => [		],	],
		'tour-manager' => [		'title' => 'Tour manager',		'fields' => [		],	],
		'guide' => [		'title' => 'Guide',		'fields' => [		],	],
		'activities-handler' => [		'title' => 'Activities handler',		'fields' => [		],	],
		'drivers' => [		'title' => 'Drivers',		'fields' => [			'name' => 'Name',			'phone' => 'Phone',			'rating' => 'Rating',			'date-of-birth' => 'Date of birth',			'drivers-license-number' => 'Drivers license number',			'drivers-license-state' => 'Drivers license state',			'drivers-license-expiration-date' => 'Drivers license expiration date',			'relationdeviceid' => 'Relationdeviceid',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',		],	],
		'booking' => [		'title' => 'Booking',		'fields' => [			'booking-id' => 'Booking id',			'full-name' => 'Full name',			'email' => 'Email',			'email2' => 'Email2',			'phone' => 'Phone',			'activated' => 'Activated',			'score' => 'Score',			'no-of-adults' => 'No of adults',			'no-of-children' => 'No of children',			'agency-id' => 'Agency id',			'agent-id' => 'Agent id',			'meal-day' => 'Meal day',			'bill-pay' => 'Bill pay',			'budget' => 'Budget',			'driver-pick-up-time' => 'Driver pick up time',			'driver-pick-up-time-updated' => 'Driver pick up time updated',			'drop-address' => 'Drop address',			'handler-name' => 'Handler name',			'handler-no' => 'Handler no',			'meals-supplement' => 'Meals supplement',			'member-of-iti' => 'Member of iti',			'package-category' => 'Package category',			'pickup-address' => 'Pickup address',			'total-price' => 'Total price',			'pickup-location' => 'Pickup location',			'tour-cost' => 'Tour cost',			'selected-car' => 'Selected car',			'status' => 'Status',			'supplier-id' => 'Supplier id',			'total-room' => 'Total room',			'total-tour-days' => 'Total tour days',			'traveller-id' => 'Traveller id',			'itinerary-places' => 'Itinerary places',			'itinerary-places-time' => 'Itinerary places time',			'tour-id' => 'Tour id',			'tour-name' => 'Tour name',			'tour-location' => 'Tour location',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',		],	],
		'group' => [		'title' => 'Group',		'fields' => [			'booking-id' => 'Booking id',			'full-name' => 'Full name',			'email' => 'Email',			'phone' => 'Phone',			'activated' => 'Activated',			'no-of-adults' => 'No of adults',			'no-of-children' => 'No of children',			'agency-id' => 'Agency id',			'agent-id' => 'Agent id',			'meal-day' => 'Meal day',			'bill-pay' => 'Bill pay',			'driver-pick-up-time' => 'Driver pick up time',			'driver-pick-up-time-updated' => 'Driver pick up time updated',			'drop-address' => 'Drop address',			'handler-name' => 'Handler name',			'handler-no' => 'Handler no',			'meals-supplement' => 'Meals supplement',			'package-category' => 'Package category',			'pickup-address' => 'Pickup address',			'pickup-location' => 'Pickup location',			'total-price' => 'Total price',			'tour-cost' => 'Tour cost',			'selected-car' => 'Selected car',			'status' => 'Status',			'supplier-id' => 'Supplier id',			'total-room' => 'Total room',			'total-tour-days' => 'Total tour days',			'traveller-id' => 'Traveller id',			'tour-id' => 'Tour id',			'itinerary-places' => 'Itinerary places',			'itinerary-places-time' => 'Itinerary places time',			'group' => 'Group',			'group-name' => 'Group name',			'group-id' => 'Group id',			'group-logo' => 'Group logo',			'group-place' => 'Group place',			'members' => 'Members',			'tour-cost-tax' => 'Tour cost tax',			'tour-handler' => 'Tour handler',			'tour-name' => 'Tour name',			'tour-location' => 'Tour location',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',		],	],
		'tour' => [		'title' => 'Tour',		'fields' => [			'title' => 'Title',			'locations' => 'Locations',			'total-tour-days' => 'Total tour days',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',		],	],
		'driver-role' => [		'title' => 'Driver role',		'fields' => [		],	],
		'tour-manager' => [		'title' => 'Driver role',		'fields' => [		],	],
		'driver-role' => [		'title' => 'Driver_role',		'fields' => [		],	],
		'driver-role' => [		'title' => 'Driver Role',		'fields' => [		],	],
		'driver-role' => [		'title' => 'Driver role',		'fields' => [		],	],
		'placesall' => [		'title' => 'Placesall',		'fields' => [		],	],
		'place' => [		'title' => 'Place',		'fields' => [			'title' => 'Title',			'description' => 'Description',			'contact-no' => 'Contact no',			'timing' => 'Timing',			'closed-day' => 'Closed day',			'time-required-to-visit' => 'Time required to visit',			'categories' => 'Categories',			'esb-visiblity' => 'Esb visiblity',			'address' => 'Address',			'place-longitude' => 'Place longitude',			'place-latitude' => 'Place latitude',			'city' => 'City',			'featured-image' => 'Featured image',			'gallery' => 'Gallery',			'cuisine' => 'Cuisine',			'recommended' => 'Recommended',			'partner' => 'Partner',			'place-tripadvisor-id' => 'Place tripadvisor id',			'city-id' => 'City id',			'created-by' => 'Created by',			'created-by-team' => 'Created by Team',		],	],
		'customer' => [		'title' => 'Customer',		'fields' => [			'name' => 'Name',			'email' => 'Email',			'account-manager' => 'Account manager',			'agree' => 'Agree',			'address' => 'Address',			'city' => 'City',			'state' => 'State',			'country' => 'Country',			'phone' => 'Phone',			'postcode' => 'Postcode',			'device' => 'Device',			'locale' => 'Locale',			'login' => 'Login',			'login-date-time' => 'Login date time',			'login-status' => 'Login status',			'mycred-default' => 'Mycred default',			'mycred-default-total' => 'Mycred default total',			'mycred-epp-mycred' => 'Mycred epp mycred',			'profile' => 'Profile',			'facebook' => 'Facebook',			'google' => 'Google',			'otp' => 'Otp',			'registered-thru' => 'Registered thru',		],	],
		'userr' => [		'title' => 'Userr',		'fields' => [			'name' => 'Name',			'email' => 'Email',			'password' => 'Password',			'role' => 'Role',			'remember-token' => 'Remember token',			'approved' => 'Approved',			'team' => 'Team',			'account-manager' => 'Account manager',			'agree' => 'Agree',			'banner-color' => 'Banner color',			'address' => 'Address',			'city' => 'City',			'state' => 'State',			'country' => 'Country',			'phone' => 'Phone',			'postcode' => 'Postcode',			'company' => 'Company',			'device' => 'Device',			'locale' => 'Locale',			'login' => 'Login',			'login-date-time' => 'Login date time',			'login-status' => 'Login status',			'logo' => 'Logo',			'mycred-default' => 'Mycred default',			'mycred-default-total' => 'Mycred default total',			'mycred-epp-mycred' => 'Mycred epp mycred',			'owners-email' => 'Owners email',		],	],
		'travellers' => [		'title' => 'Travellers',		'fields' => [			'name' => 'Name',			'email' => 'Email',			'display-name' => 'Display name',			'phone' => 'Phone',			'address' => 'Address',			'fcm-token' => 'Fcm token',			'device' => 'Device',			'auth-key' => 'Auth key',			'otp' => 'Otp',		],	],
		'task' => [		'title' => 'Task',		'fields' => [			'agency-id' => 'Agency id',			'agent-id' => 'Agent id',			'agent-name' => 'Agent name',			'assign-date' => 'Assign date',			'due-date' => 'Due date',			'ref-id' => 'Ref id',			'reminder' => 'Reminder',			'reminder-time' => 'Reminder time',			'remark' => 'Remark',			'status' => 'Status',		],	],
	'qa_create' => 'बनाइ (क्रिएट)',
	'qa_save' => 'सुरक्षित',
	'qa_edit' => 'संपादित (एडिट)',
	'qa_view' => 'देख',
	'qa_update' => 'सुधार',
	'qa_list' => 'सूची',
	'qa_no_entries_in_table' => '',
	'qa_custom_controller_index' => 'विशेष(कस्टम) कंट्रोलर इंडेक्स ।',
	'qa_logout' => 'लोग आउट',
	'qa_add_new' => 'नया',
	'qa_are_you_sure' => '',
	'qa_back_to_list' => 'सूची',
	'qa_dashboard' => 'बोर्ड ',
	'qa_delete' => '',
	'quickadmin_title' => 'Travelexic',
];